/**
 * Icon generator. No canvas, no image libraries: signed-distance shapes rasterised
 * with 6x supersampling, encoded straight to PNG with node:zlib.
 *
 *   node scripts/make-icons.mjs
 *
 * The mark: an hourglass (time passing while the AI works) on a dark rounded tile,
 * with a green dot for "an answer has landed". Deterministic, so the committed PNGs
 * can always be regenerated byte for byte.
 */
import { deflateSync } from 'node:zlib';
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const OUT = path.join(root, 'src', 'assets');

const SIZES = [16, 32, 48, 128];
const SS = 6; // supersamples per axis

// Palette
const TILE = [0x17, 0x17, 0x1a];
const TILE_TOP = [0x1f, 0x1f, 0x24];
const EDGE = [0xff, 0xff, 0xff];
const SAND = [0xe8, 0xa3, 0x3d];
const SAND_DIM = [0xc8, 0x86, 0x2c];
const DOT = [0x2f, 0x7d, 0x4f];

const clamp01 = (n) => (n < 0 ? 0 : n > 1 ? 1 : n);
const mix = (a, b, t) => a.map((v, i) => v + (b[i] - v) * t);

/** Signed distance to a rounded box centred at the origin. */
function sdRoundBox(px, py, half, radius) {
  const qx = Math.abs(px) - half + radius;
  const qy = Math.abs(py) - half + radius;
  const outside = Math.hypot(Math.max(qx, 0), Math.max(qy, 0));
  return outside + Math.min(Math.max(qx, qy), 0) - radius;
}

/**
 * Colour of one supersampled point. p is in [-1, 1] on both axes, y downwards.
 * Returns [r, g, b, a].
 */
function shade(px, py) {
  // Tile
  const tile = sdRoundBox(px, py, 0.985, 0.44);
  if (tile > 0) return [0, 0, 0, 0];

  let color = mix(TILE, TILE_TOP, clamp01((1 - py) / 2));
  // A hairline edge keeps the mark legible on light and dark toolbars alike.
  const edge = clamp01(1 - Math.abs(tile) / 0.06);
  color = mix(color, EDGE, edge * 0.16);

  // Hourglass: two caps and a bowtie between them.
  const gx = px / 0.44;
  const gy = py / 0.5;
  const capTop = Math.abs(gy + 0.86) <= 0.14 && Math.abs(gx) <= 0.66;
  const capBottom = Math.abs(gy - 0.86) <= 0.14 && Math.abs(gx) <= 0.66;
  const waistHalf = 0.66 * (Math.abs(gy) / 0.74);
  const bowtie = Math.abs(gy) <= 0.76 && Math.abs(gx) <= waistHalf;
  if (capTop || capBottom || bowtie) {
    // A little vertical shading so it reads as glass and sand, not a flat glyph.
    const shaded = mix(SAND, SAND_DIM, clamp01((py + 0.5) / 1.2) * 0.55);
    color = shaded;
  }

  // Green dot: an answer has landed.
  const ddx = px - 0.6;
  const ddy = py - 0.6;
  const dist = Math.hypot(ddx, ddy);
  if (dist <= 0.52) color = mix(color, TILE, clamp01((0.52 - dist) / 0.12) * 0.9);
  if (dist <= 0.36) color = mix(color, DOT, clamp01((0.36 - dist) / 0.05));
  if (dist <= 0.34) color = DOT;

  return [Math.round(color[0]), Math.round(color[1]), Math.round(color[2]), 255];
}

function renderIcon(size) {
  const big = size * SS;
  const out = Buffer.alloc(size * size * 4);
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;
      for (let sy = 0; sy < SS; sy += 1) {
        for (let sx = 0; sx < SS; sx += 1) {
          const px = ((x * SS + sx + 0.5) / big) * 2 - 1;
          const py = ((y * SS + sy + 0.5) / big) * 2 - 1;
          const [cr, cg, cb, ca] = shade(px, py);
          const alpha = ca / 255;
          r += cr * alpha;
          g += cg * alpha;
          b += cb * alpha;
          a += alpha;
        }
      }
      const n = SS * SS;
      const idx = (y * size + x) * 4;
      out[idx] = a > 0 ? Math.round(r / a) : 0;
      out[idx + 1] = a > 0 ? Math.round(g / a) : 0;
      out[idx + 2] = a > 0 ? Math.round(b / a) : 0;
      out[idx + 3] = Math.round((a / n) * 255);
    }
  }
  return out;
}

// --- PNG encoding ------------------------------------------------------------

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i += 1) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([length, typeBuf, data, crc]);
}

function encodePNG(size, rgba) {
  const stride = size * 4;
  const raw = Buffer.alloc((stride + 1) * size);
  for (let y = 0; y < size; y += 1) {
    raw[y * (stride + 1)] = 0; // filter: none
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // truecolour with alpha
  ihdr[10] = 0;
  ihdr[11] = 0;
  ihdr[12] = 0;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

await mkdir(OUT, { recursive: true });
for (const size of SIZES) {
  const png = encodePNG(size, renderIcon(size));
  const file = path.join(OUT, `icon-${size}.png`);
  await writeFile(file, png);
  console.log(`${path.relative(root, file)}  ${png.length} bytes`);
}
